[tox]

envlist =
    flake8, black, mypy
    test-py{310,311,312,313,314,py3}
    coverage_report
    docs
    packaging

skip_missing_interpreters = {tty:True:False}


[default]

basepython = python3.14

deps =

setenv =
    PY_MODULE=hyperlink

    PYTHONPYCACHEPREFIX={envtmpdir}/pycache


##
# Default environment: unit tests
##

[testenv]

description = run tests

basepython =
    py: python

    py10: python3.10
    py11: python3.11
    py12: python3.12
    py13: python3.13
    py14: python3.14

    py3: pypy3

deps =
    # For pytest
    py{310,311,312,313,314,py3}: pytest==9.0.2

    # For code coverage
    {[testenv:coverage_report]deps}
    py{310,311,312,313,314,py3}: pytest-cov==7.0.0

    # For hypothesis.
    py{310,311,312,313,314,py3}: hypothesis==6.151.9

setenv =
    {[default]setenv}

    COVERAGE_FILE={toxworkdir}/coverage.{envname}
    HYPOTHESIS_STORAGE_DIRECTORY={toxworkdir}/hypothesis

passenv = CI

commands =
    pytest --cov={env:PY_MODULE} --cov-report=term-missing:skip-covered --doctest-modules {posargs:src/{env:PY_MODULE}}
    coverage_xml: coverage xml


##
# Black code formatting
##

[testenv:black]

description = run Black (linter)

basepython = {[default]basepython}

skip_install = True

deps =
    black==26.1.0

setenv =
    BLACK_LINT_ARGS=--check

commands =
    black {env:BLACK_LINT_ARGS:} {posargs:setup.py src}


[testenv:black-reformat]

description  = {[testenv:black]description} and reformat
basepython   = {[testenv:black]basepython}
skip_install = {[testenv:black]skip_install}
deps         = {[testenv:black]deps}
commands     = {[testenv:black]commands}


##
# Flake8 linting
##

[testenv:flake8]

description = run Flake8 (linter)

basepython = {[default]basepython}

skip_install = True

deps =
    flake8-bugbear==25.11.29
    flake8==7.3.0
    mccabe==0.7.0
    pep8-naming==0.15.1
    pycodestyle==2.14.0
    pydocstyle==6.3.0
    pyflakes==3.4.0

commands =
    flake8 {posargs:setup.py src/{env:PY_MODULE}}


[flake8]

# !!! BRING THE PAIN !!!
select = A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z

show-source  = True
doctests     = True

max-line-length = 80

# Codes: http://flake8.pycqa.org/en/latest/user/error-codes.html
ignore =
    # syntax error in type comment
    F723,

    # function name should be lowercase
    N802,

    # argument name should be lowercase
    N803,

    # variable in function should be lowercase
    N806,

    # variable in class scope should not be mixedCase
    N815,

    # variable in global scope should not be mixedCase
    N816,

    # line break before binary operator
    W503,

    # End of list (allows last item to end with trailing ',')
    EOL

# flake8-import-order: local module name space
application-import-names = deploy


##
# Mypy static type checking
##

[testenv:mypy]

description = run Mypy (static type checker)

basepython = {[default]basepython}

deps =
    mypy==1.19.1
    types-mock==5.2.0.20250924

    {[default]deps}

commands =
    mypy                                       \
        --config-file="{toxinidir}/tox.ini"    \
        --cache-dir="{toxworkdir}/mypy_cache"  \
        {tty:--pretty:}                        \
        {posargs:src}


[mypy]

# Global settings

check_untyped_defs       = True
disallow_any_generics    = True
disallow_incomplete_defs = True
disallow_untyped_defs    = True
no_implicit_optional     = True
show_column_numbers      = True
show_error_codes         = True
strict_optional          = True
warn_no_return           = True
warn_redundant_casts     = True
warn_return_any          = True
warn_unreachable         = True
warn_unused_ignores      = True

# DrawCallable is generic

[mypy-hyperlink.hypothesis]
disallow_any_generics = False
[mypy-hyperlink.test.test_hypothesis]
disallow_any_generics = False

# Don't complain about dependencies known to lack type hints

[mypy-hypothesis]
ignore_missing_imports = True
[mypy-hypothesis.*]
ignore_missing_imports = True

[mypy-idna]
ignore_missing_imports = True


##
# Coverage report
##

[testenv:coverage_report]

description = generate coverage report

depends = test-py{310,311,312,313,314}

basepython = {[default]basepython}

skip_install = True

deps =
    coverage==7.13.4

setenv =
    {[default]setenv}

    COVERAGE_FILE={toxworkdir}/coverage

commands =
    coverage combine
    - coverage report
    - coverage html


##
# Codecov
##

[testenv:codecov]

description = upload coverage to Codecov

depends = {[coverage_report]depends}

basepython = python

skip_install = True

deps =
    {[testenv:coverage_report]deps}
    codecov

passenv =
    # See https://github.com/codecov/codecov-python/blob/master/README.md#using-tox
    # And CI-specific docs:
    #   https://help.github.com/en/articles/virtual-environments-for-github-actions#default-environment-variables
    #   https://docs.travis-ci.com/user/environment-variables#default-environment-variables
    #   https://www.appveyor.com/docs/environment-variables/
    TOXENV CODECOV_* CI
    GITHUB_*
    TRAVIS TRAVIS_*
    APPVEYOR APPVEYOR_*

setenv =
    {[testenv:coverage_report]setenv}

    COVERAGE_XML={envlogdir}/coverage.xml

commands =
    # Note documentation for CI variables in passenv above
    coverage combine
    coverage xml -o "{env:COVERAGE_XML}"
    codecov --file="{env:COVERAGE_XML}" --env                 \
        GITHUB_REF GITHUB_COMMIT GITHUB_USER GITHUB_WORKFLOW  \
        TRAVIS_BRANCH TRAVIS_BUILD_WEB_URL                    \
        TRAVIS_COMMIT TRAVIS_COMMIT_MESSAGE                   \
        APPVEYOR_REPO_BRANCH APPVEYOR_REPO_COMMIT             \
        APPVEYOR_REPO_COMMIT_AUTHOR_EMAIL                     \
        APPVEYOR_REPO_COMMIT_MESSAGE_EXTENDED


##
# Documentation
##

[testenv:docs]

description = build documentation

basepython = {[default]basepython}

deps =
    Sphinx==9.1.0
    sphinx-rtd-theme==3.1.0

commands =
    sphinx-build                           \
        -b html -d "{envtmpdir}/doctrees"  \
        "{toxinidir}/docs"                 \
        "{toxinidir}/htmldocs"


[testenv:docs-auto]

description = build documentation and rebuild automatically

basepython = {[default]basepython}

deps =
    {[testenv:docs]deps}
    sphinx-autobuild==2025.8.25

commands =
    sphinx-autobuild                       \
        -b html -d "{envtmpdir}/doctrees"  \
        --host=localhost                   \
        "{toxinidir}/docs"                 \
        "{toxinidir}/htmldocs"


##
# Packaging
##

[testenv:packaging]

description = check for potential packaging problems

basepython = {[default]basepython}

skip_install = True

deps =
   check-manifest==0.51
   readme-renderer==44.0
   twine==6.2.0

commands =
   check-manifest
   pip wheel --wheel-dir "{envtmpdir}/dist" --no-deps {toxinidir}
   twine check "{envtmpdir}/dist/"*


##
# Print dependencies
##

[testenv:dependencies]

description = print dependencies

basepython = {[default]basepython}

recreate = true

deps =

commands =
    pip freeze --exclude={env:PY_MODULE}
